# Usa uma imagem leve do Node.js
FROM node:20-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copia os arquivos de dependência e instala
COPY package*.json ./
RUN npm install --legacy-peer-deps

# !!! COPIA O CÓDIGO PRIMEIRO !!!
# Isso coloca o prisma/schema.prisma dentro do container
COPY . .

# !!! GERA O CLIENTE DEPOIS !!!
# Agora ele vai encontrar o arquivo schema.prisma
RUN npx prisma generate

# Expõe a porta que o NestJS usa
EXPOSE 3000

# Comando para rodar a aplicação em modo de desenvolvimento
CMD ["npm", "run", "start:dev"]