services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swagger_and_nestjs_through_typescript_api_ui
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:minha_senha_secreta@db:5432/nestjs_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minha_senha_secreta
      POSTGRES_DB: nestjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: