openapi: 3.0.0
info:
  title: API de Autenticação com Node.js com foco em Typescript, Swagger e senha com Hash via bcrypt
  description: API de estudo para gerenciamento de usuários e autenticação JWT.
  version: 1.1.0

servers:
  - url: http://localhost:3000
    description: Servidor de Desenvolvimento

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginDto:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          example: "user@example.com"
        password:
          type: string
          example: "Lucas123456"

    RegisterDto:
      type: object
      required: [name, email, password]
      properties:
        name:
          type: string
          example: "Lucas Paguetti"
        email:
          type: string
          example: "lucas@cesar.school"
        password:
          type: string
          example: "Lucas123456"

paths:
  /auth/register:
    post:
      summary: Cadastrar um novo usuário
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: Usuário criado com sucesso ✅
        '409':
          description: E-mail já cadastrado ❌

  /auth/login:
    post:
      summary: Autenticar usuário e receber JWT
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: Sucesso ✅
          content:
            application/json:
              example:
                access_token: "eyJhbG..."
        '401':
          description: Credenciais inválidas ❌

  /auth/profile:
    get:
      summary: Consultar dados do perfil do usuário autenticado
      tags: [Auth]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dados retornados ✅
        '401':
          description: Não autorizado ❌